using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using IncriElemental.Core.Engine;
using IncriElemental.Core.Models;
using IncriElemental.Desktop.Visuals;
using System;
using System.Collections.Generic;
using System.Linq;

namespace IncriElemental.Desktop;

public class Game1 : Game
{
    private GraphicsDeviceManager _graphics;
    private SpriteBatch _spriteBatch;
    private GameEngine _engine;
    private ParticleSystem _particles;
    private MouseState _lastMouseState;
    private Texture2D _pixel;
    private List<string> _log = new();
    private const int MaxLogLines = 5;

    public Game1()
    {
        _graphics = new GraphicsDeviceManager(this);
        Content.RootDirectory = "Content";
        IsMouseVisible = true;
        _engine = new GameEngine();
    }

    protected override void Initialize()
    {
        _graphics.PreferredBackBufferWidth = 1024;
        _graphics.PreferredBackBufferHeight = 768;
        _graphics.ApplyChanges();

        base.Initialize();
        _particles = new ParticleSystem(GraphicsDevice);
        _pixel = new Texture2D(GraphicsDevice, 1, 1);
        _pixel.SetData(new[] { Color.White });
        
        AddToLog("You awaken in the void.");
    }

    protected override void LoadContent()
    {
        _spriteBatch = new SpriteBatch(GraphicsDevice);
        // Note: We use .xnb files generated by MGCB. 
        // If the font fails to load (e.g. build issues in CLI), we'll skip text rendering.
        try {
            _font = Content.Load<SpriteFont>("main_font");
        } catch { }
    }

    private void AddToLog(string message)
    {
        _log.Insert(0, message);
        if (_log.Count > MaxLogLines) _log.RemoveAt(MaxLogLines);
    }

    protected override void Update(GameTime gameTime)
    {
        var mouseState = Mouse.GetState();
        var deltaTime = (float)gameTime.ElapsedGameTime.TotalSeconds;
        
        if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
            Exit();

        _engine.Update(deltaTime);
        _particles.Update(deltaTime);

        // Interaction Logic
        if (mouseState.LeftButton == ButtonState.Pressed && _lastMouseState.LeftButton == ButtonState.Released)
        {
            var center = new Vector2(512, 384);
            var focusRect = new Rectangle(412, 334, 200, 100);
            
            if (focusRect.Contains(mouseState.Position))
            {
                _engine.Focus();
                _particles.EmitFocus(center);
                if (_engine.State.GetResource(ResourceType.Aether).Amount == 1) AddToLog("Aether flows...");
                if (_engine.State.Discoveries["void_observed"] && _log[0] != "The void is thick with potential.") AddToLog("The void is thick with potential.");
            }

            if (_engine.State.GetResource(ResourceType.Aether).Amount >= 10 || _engine.State.Discoveries["first_manifestation"])
            {
                var manifestRect = new Rectangle(412, 450, 200, 50);
                if (manifestRect.Contains(mouseState.Position))
                {
                    if (_engine.Manifest("speck"))
                    {
                        AddToLog("A speck of matter appears.");
                        for (int i = 0; i < 20; i++)
                            _particles.AddParticle(new Vector2(512, 475), new Vector2((float)(Random.Shared.NextDouble() - 0.5) * 200, (float)(Random.Shared.NextDouble() - 0.5) * 200), Color.SaddleBrown, 1f);
                    }
                }
            }

            if (_engine.State.GetResource(ResourceType.Aether).Amount >= 30 || _engine.State.Discoveries["automation_unlocked"])
            {
                var automationRect = new Rectangle(412, 510, 200, 50);
                if (automationRect.Contains(mouseState.Position))
                {
                    if (_engine.Manifest("rune_of_attraction"))
                    {
                        AddToLog("The aether begins to flow of its own accord.");
                        for (int i = 0; i < 20; i++)
                            _particles.AddParticle(new Vector2(512, 535), new Vector2((float)(Random.Shared.NextDouble() - 0.5) * 200, (float)(Random.Shared.NextDouble() - 0.5) * 200), Color.Plum, 1f);
                    }
                }
            }
        }

        _lastMouseState = mouseState;
        base.Update(gameTime);
    }

    protected override void Draw(GameTime gameTime)
    {
        GraphicsDevice.Clear(new Color(5, 5, 10));

        _spriteBatch.Begin();

        _particles.Draw(_spriteBatch);

        // Focus Button
        var pulse = (float)Math.Sin(gameTime.TotalGameTime.TotalSeconds * 3) * 0.1f + 0.9f;
        _spriteBatch.Draw(_pixel, new Rectangle(412, 334, 200, 100), Color.MediumPurple * 0.3f * pulse);
        
        if (_font != null)
        {
            _spriteBatch.DrawString(_font, "FOCUS", new Vector2(512 - _font.MeasureString("FOCUS").X / 2, 384 - _font.MeasureString("FOCUS").Y / 2), Color.White);

            // Resource Indicators
            var aether = _engine.State.GetResource(ResourceType.Aether);
            _spriteBatch.DrawString(_font, $"Aether: {aether.Amount:F1}", new Vector2(412, 310), Color.MediumPurple);

            // Manifestation Button
            if (aether.Amount >= 10 || _engine.State.Discoveries["first_manifestation"])
            {
                _spriteBatch.Draw(_pixel, new Rectangle(412, 450, 200, 50), Color.SaddleBrown * 0.4f);
                _spriteBatch.DrawString(_font, "MANIFEST SPECK (10 Aether)", new Vector2(512 - _font.MeasureString("MANIFEST SPECK (10 Aether)").X / 2, 475 - _font.MeasureString("MANIFEST SPECK (10 Aether)").Y / 2), Color.Tan);
            }

            // Rune of Attraction
            if (aether.Amount >= 30 || _engine.State.Discoveries["automation_unlocked"])
            {
                _spriteBatch.Draw(_pixel, new Rectangle(412, 510, 200, 50), Color.MediumPurple * 0.4f);
                _spriteBatch.DrawString(_font, "RUNE OF ATTRACTION (30 Aether)", new Vector2(512 - _font.MeasureString("RUNE OF ATTRACTION (30 Aether)").X / 2, 535 - _font.MeasureString("RUNE OF ATTRACTION (30 Aether)").Y / 2), Color.Plum);
            }

            // Earth Indicator
            if (_engine.State.Discoveries["first_manifestation"])
            {
                var earth = _engine.State.GetResource(ResourceType.Earth);
                _spriteBatch.DrawString(_font, $"Earth Essence: {earth.Amount:F1}", new Vector2(412, 570), Color.SaddleBrown);
            }

            // Narrative Log
            for (int i = 0; i < _log.Count; i++)
            {
                float alpha = 1.0f - (i * 0.2f);
                _spriteBatch.DrawString(_font, _log[i], new Vector2(20, 20 + (i * 20)), Color.Gray * alpha);
            }
        }

        _spriteBatch.End();

        base.Draw(gameTime);
    }
}
