import os
import subprocess
import time

def generate_gallery():
    print("Generating Visual Gallery...")
    
    # Run the game with the capture script
    # Need to find the executable path
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target_dir = os.path.join(base_dir, "src", "IncriElemental.Desktop", "bin", "Debug", "net10.0")
    exe_path = os.path.join(target_dir, "IncriElemental.Desktop.exe")
    
    if not os.path.exists(exe_path):
        # Try to build first
        print("Executable not found. Building project...")
        subprocess.run(["dotnet", "build", os.path.join(base_dir, "IncriElemental.slnx")], check=True)
        
    cmd = [exe_path, "--ai-mode"]
    # Copy script to ai_commands.txt
    ai_script = os.path.join(base_dir, "prompts", "gallery_capture.txt")
    target_script = os.path.join(target_dir, "ai_commands.txt")
    
    with open(ai_script, 'r') as f:
        script = f.read()
    with open(target_script, 'w') as f:
        f.write(script)
        
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, cwd=target_dir, check=False)
    
    # Collect results from target_dir/review to base_dir/review
    # Actually AiModeSystem saves in Path.Combine("review", n) relative to CWD
    live_review = os.path.join(target_dir, "review")
    base_review = os.path.join(base_dir, "review")
    
    if not os.path.exists(base_review):
        os.makedirs(base_review)
        
    # Walk and move/copy
    files = [f for f in os.listdir(live_review) if f.endswith(".png")]
    print(f"Found {len(files)} screenshots.")
    
    gallery_md = "# 🌌 IncriElemental Visual Gallery\n\n"
    gallery_md += "This gallery is automatically generated by `scripts/generate_gallery.py`.\n\n"
    
    for f in sorted(files):
        # Move to base_review
        src = os.path.join(live_review, f)
        dst = os.path.join(base_review, f)
        if os.path.exists(dst): os.remove(dst)
        os.rename(src, dst)
        
        name = f.replace(".png", "").replace("_", " ").title()
        gallery_md += f"## {name}\n"
        gallery_md += f"![{name}](./{f})\n\n"
        
    with open(os.path.join(base_review, "gallery.md"), 'w', encoding='utf-8') as f:
        f.write(gallery_md)

        
    print(f"Gallery generated at {os.path.join(base_review, 'gallery.md')}")

if __name__ == "__main__":
    generate_gallery()
